version: '3.3'
services:
  webscrapper:
      container_name: webscrapper
      build: .
      depends_on:
        - mysqldb
      environment:
        FASTAPI_PORT: ${FASTAPI_PORT:-9000}
      ports:
        - $FASTAPI_PORT:$FASTAPI_PORT
      restart: always
      networks:
        - app-tier
  mysqldb:
      image: mysql:8.1.0
      restart: always
      container_name: mysqldb
      environment:
        DB_USER: ${DB_USER:-root}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      volumes:
        - ./data:/data/db
      ports:
        - 127.0.0.1:3306:3306
      networks:
        - app-tier
networks:
  app-tier:
    driver: bridge

