FROM python:alpine3.18

# required by mysqlclient
RUN apk --no-cache add mariadb-dev build-base
COPY pip-requirements.txt .
COPY pip-requirements-test.txt .

RUN pip install --no-cache-dir -r pip-requirements.txt
RUN pip install --no-cache-dir -r pip-requirements-test.txt

COPY app /app
COPY tests /tests

ENV PYTHONPATH=/app:$PYTHONPATH

CMD ["python", "-m", "unittest", "discover", "tests"]

