version: '3.3'
services:
  webscrapper:
      container_name: webscrapper
      build: .
      depends_on:
        - mysqldb
      environment:
        FASTAPI_PORT: ${FASTAPI_PORT}
        SERVER_IP: ${SERVER_IP}
        DB_NAME: ${DB_NAME}
        INTERNAL_DB_ADDRESS: ${INTERNAL_DB_ADDRESS}
      ports:
        - $FASTAPI_PORT:$FASTAPI_PORT
      restart: always
      networks:
        - app-tier
  mysqldb:
      image: mysql:8.1.0
      restart: always
      container_name: mysqldb
      environment:
        SERVER_IP: ${SERVER_IP}
        DB_USER: ${DB_USER}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      volumes:
        - ./data:/data/db
      ports:
        - $SERVER_IP:3306:3306
      networks:
        - app-tier
networks:
  app-tier:
    driver: bridge

